[project]
name = "hlogger"
version = "0.1.0"
description = "Hridayangam Logger"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "logfire>=0.53.0",
    "structlog>=24.4.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
